{
 "title": "Rogers Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Slice Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (snssai) (slice_throughput{direction=\"uplink\"})",
     "legendFormat": "snssai={{snssai}}"
    }
   ]
  },
  {
   "title": "Slice Throughput (Slice 1)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "slice_throughput{direction=\"uplink\", snssai=\"1@010203\"}",
     "legendFormat": "seid={{seid}}"
    }
   ]
  },
  {
   "title": "Slice Throughput (Slice 2)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "slice_throughput{direction=\"uplink\", snssai=\"1@112233\"}",
     "legendFormat": "seid={{seid}}"
    }
   ]
  },
  {
   "title": "Slice Throughput (Slice 3)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "slice_throughput{direction=\"uplink\", snssai=\"1@000001\"}",
     "legendFormat": "seid={{seid}}"
    }
   ]
  }
 ]
}