{
 "title": "Monarch Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Slice 1 (SNSSAI = 1-000001)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downlink Slice Throughput at UPF (Slice 1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "slice_throughput{direction=\"downlink\", snssai=\"1-000001\"}",
     "legendFormat": "seid={{seid}}"
    }
   ]
  },
  {
   "title": "Uplink Slice Throughput at UPF (Slice 1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "slice_throughput{direction=\"uplink\", snssai=\"1-000001\"}",
     "legendFormat": "seid={{seid}}"
    }
   ]
  },
  {
   "title": "Slice 2 (SNSSAI = 2-000002)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Downlink Slice Throughput at UPF (Slice 2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "slice_throughput{direction=\"downlink\", snssai=\"2-000002\"}",
     "legendFormat": "seid={{seid}}"
    }
   ]
  },
  {
   "title": "Uplink Slice Throughput at UPF (Slice 2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "slice_throughput{direction=\"uplink\", snssai=\"2-000002\"}",
     "legendFormat": "seid={{seid}}"
    }
   ]
  }
 ]
}